CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE JURIDISK_VURDERING
(
    ID                 VARCHAR(36) DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    FNR                VARCHAR(11)              NOT NULL,
    OPPRETTET          TIMESTAMP WITH TIME ZONE NOT NULL,
    JURIDISK_VURDERING TEXT                     NOT NULL
);


CREATE INDEX JURIDISK_VURDERING_FNR_INDEX
    ON JURIDISK_VURDERING (FNR);
